export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  ADMIN_DASHBOARD: "/admin",
  MANAGE: "/manage",
  TEACHER_DASHBOARD: "/teacher",
  TEACHER_CLASSROOMS: "/teacher/classrooms",
  STUDENT_DASHBOARD: "/student",
  STUDENT_CALENDAR: "/student/calendar",
  STUDENT_GRADES: "/student/grades",
  ASSIGNMENTS: "/assignments",
  CREATE_ASSIGNMENT: "/assignments/create",
  ASSIGNMENT_DETAILS: (id: number | string) => `/assignments/${id}`,
  EDIT_ASSIGNMENT: (id: number | string) => `/assignments/${id}/edit`,
  SUBMISSIONS: "/submissions",
  APPROVALS: "/approvals",
  SUBMISSION_DETAILS: (id: number | string) => `/submissions/${id}`,
  ADMIN_RESULTS: "/admin/results",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  UNAUTHORIZED: "/unauthorized",
} as const;
